# Generated by Django 4.2 on 2023-12-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lashservice',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
