# Generated by Django 4.2 on 2023-12-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_reserveservice_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveservice',
            name='fixed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
