# Generated by Django 4.2 on 2024-01-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_reserveservice_fixed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lashservice',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lashservice',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
