# Generated by Django 4.2 on 2024-01-06 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0022_alter_profile_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='اکستنشن مژه', max_length=300)),
                ('course_sessions', models.IntegerField(default=5)),
                ('course_start_date', models.DateTimeField(auto_now_add=True)),
                ('course_duration', models.TimeField(null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('comment', models.TextField(max_length=300, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.profile')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='users.profile')),
            ],
        ),
    ]
