# Generated by Django 4.2 on 2024-01-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='course',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
