# Generated by Django 4.2 on 2024-01-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_is_finished_course_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_capacity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
