# Generated by Django 4.2 on 2024-01-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_student_coursereservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_duration',
        ),
        migrations.AddField(
            model_name='course',
            name='course_session_duration',
            field=models.IntegerField(null=True),
        ),
    ]
