# Generated by Django 4.2.7 on 2023-12-27 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertype_user_address_user_birth_date_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=uuid.UUID('5946d2de-6d8b-49f2-9bc3-5cf4b8d13e3a'), max_length=300, verbose_name='uid'),
        ),
    ]
