# Generated by Django 4.2 on 2023-12-28 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1e984c20-91f0-4b08-9f8d-8e7d13ecafa0'), max_length=300, verbose_name='uid'),
        ),
    ]
