# Generated by Django 4.2 on 2023-12-28 04:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('6e4875be-bbbe-420e-b586-a002c2f6edee'), max_length=300, verbose_name='uid'),
        ),
    ]
