# Generated by Django 4.2 on 2023-12-28 04:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_username_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='password', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='username', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a3b260fa-87e0-4a03-9554-946273b7d584'), max_length=300, verbose_name='uid'),
        ),
    ]
