# Generated by Django 4.2 on 2023-12-28 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('040bb67a-1527-41b1-955f-9eb95203410e'), max_length=300, verbose_name='uid'),
        ),
    ]
