# Generated by Django 4.2 on 2023-12-30 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cfd8d124-09a4-4c98-95dc-ec6762f729b9'), max_length=300, verbose_name='uid'),
        ),
    ]
