# Generated by Django 4.2 on 2023-12-30 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('512f479a-9660-4aa7-ada5-1dee05ec6f93'), max_length=300, verbose_name='uid'),
        ),
    ]
