# Generated by Django 4.2 on 2023-12-30 05:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('41f8ce78-ca89-4a22-8e30-9708fd18b8d7'), max_length=300, verbose_name='uid'),
        ),
    ]
