# Generated by Django 4.2 on 2023-12-30 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e850e899-277f-4112-8f79-25a37e0ee7c8'), max_length=300, verbose_name='uid'),
        ),
    ]
