# Generated by Django 4.2 on 2023-12-30 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('df1e0ada-4106-461e-9b6f-f7cecd8b53cd'), max_length=300, verbose_name='uid'),
        ),
    ]
