# Generated by Django 4.2 on 2024-01-06 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('671413c1-43b0-4fa9-ba47-1c386050d1bb'), max_length=300, verbose_name='uid'),
        ),
    ]
