# Generated by Django 4.2 on 2024-01-06 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('9fac4413-3e44-4de1-96c2-41c4aabc1b23'), max_length=300, verbose_name='uid'),
        ),
    ]
