# Generated by Django 4.2 on 2024-01-06 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d83c15cd-cb22-44e1-a563-ea09afd11536'), max_length=300, verbose_name='uid'),
        ),
    ]
