# Generated by Django 4.2 on 2024-01-06 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('3afe2c13-8504-412c-8d60-2c924ed8eca4'), max_length=300, verbose_name='uid'),
        ),
    ]
