# Generated by Django 4.2 on 2024-01-11 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('c61b362d-e6dc-40fb-89e0-8e574c949c63'), max_length=300, verbose_name='uid'),
        ),
    ]
