# Generated by Django 4.2 on 2024-01-11 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('fb4ba702-2eb9-438b-bfdf-912bb6d56da4'), max_length=300, verbose_name='uid'),
        ),
    ]
