import os

DEFAULT_FILE_STORAGE = os.getenv('DEFAULT_FILE_STORAGE')
AWS_ACCESS_KEY_ID = os.getenv('ARVAN_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('ARVAN_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('ARVAN_STORAGE_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.getenv('ARVAN_ENDPOINT_URL')
AWS_S3_REGION_NAME = os.getenv('ARVAN_STORAGE_REGION_NAME')
AWS_STORAGE_DEFAULT_ACL = os.getenv('ARVAN_STORAGE_DEFAULT_ACL')
# AWS_DEFAULT_ACL = env("ARVAN_STORAGE_DEFAULT_ACL")
